device.mk
you need to add these five binaries:
vendor/firmware/keymaster/keymaster.b00
vendor/firmware/keymaster/keymaster.b01
vendor/firmware/keymaster/keymaster.b02
vendor/firmware/keymaster/keymaster.b03
vendor/firmware/keymaster/keymaster.mdt
=> rhine: build keystore

rootdir/init.rhine.rc, rootdir/system/etc/init.rhine.bt.sh, rootdir/ueventd.rhine.rc
It was anyway wrong and on 3.10 kernel those changes are
required for BTS402x to get initialized correctly.
=> Fix bluetooth initialization

BoardConfig.mk
This is just wrong, and hardcoded paths are always bad.
If anything, this should use $(OUT_DIR), or the proper kernel paths as needed.
=> Revert "Move dtbs files to out directory."

BoardConfig.mk
rhine was upgraded to v2 in 3.10 kernel
=> mkqcdtbootimg:  --dt_version 2

rootdir/init.rhine.pwr.rc, rootdir/init.rhine.rc
While this may be good when booting the system, it's actually really
bad for kernel. Remove lines that will mess with the I/O scheduler
and its configuration to follow kernel defaults.
=> [RHINE] init: Remove I/O scheduler changes. Follow kernel defaults.

BoardConfig.mk
BOARD_USES_GENERIC_AUDIO is obsolete
https://android.googlesource.com/platform/hardware/libhardware_legacy/+/android-5.0.2_r1/audio/Android.mk
=> BOARD_USES_GENERIC_AUDIO

rootdir/init.rhine.rc
Reverts sonyxperiadev/device-sony-rhine#42
It *should* not be world readable, as it contains the IMEI and serial number.
=> Revert "rhine: fix cmdline permission"

rootdir/ueventd.rhine.rc
needed by libqdutils and libqdMetaData
will be needed too for camera in future
=> rhine: Fix video nodes permission

device.mk
Honami, Amami and Togari are calling: aosp_base.mk
telephony.mk
in AOSP telephony.mk is calling (Dialer): https://android.googlesource.com/platform/build/+/android-5.1.0_r3/target/product/telephony.mk
in AOSP aosp_base.mk calls others .mk as core.mk who is calling (Email and Exchange2) (Strings 35 and 36): https://android.googlesource.com/platform/build/+/android-5.1.0_r3/target/product/core.mk
=> rhine: remove overrides packages

overlay/packages/services/Telephony/res/values/config.xml
also telephony.lteOnGsmDevice=1 is set in system.prop
=> rhine: Enable LTE

system.prop
=> rhine: remove double LTE prop

overlay/packages/services/Telephony/res/values/config.xml
This is set false by default in AOSP. see (string 54): https://android.googlesource.com/platform/packages/services/Telephony/+/android-5.1.1_r1/res/values/config.xml
=> rhine: remove override world phone overlay

device.mk
AOSP builds is ignoring our audio_effects.conf at the start of build.
Correct the paths instead of system/etc/audio_effects.conf ---> system/vendor/etc/audio_effects.conf as hammerhead
See (string 170): https://android.googlesource.com/device/lge/hammerhead/+/android-5.1.1_r1/device.mk
=> rhine: copy audio_effects to correct way

BoardConfig.mk
Currently, the FrameBuffer in AOSP is double-buffering.
That's bad in cases when Compositor takes time near 16ms or less.
There're so many blockers('WaitForever') in several composition periods which makes janks. While we make it triple-buffering, those blockers disappear
=> rhine: set Num of surface buffers to 3

rootdir/init.rhine.rc
=> init.rhine.rc: Remove /data/misc/wifi/sockets

rootdir/init.rhine.pwr.rc
the correct path is /dev/cpuctl/cpu.notify_on_migrate not /dev/cpuctl/apps/cpu.notify_on_migrate
=> rhine: Fix path to cpuctl

rootdir/init.rhine.rc, rootdir/ueventd.rhine.rc
deleted not exist format_3d: ls -l /sys/class/graphics/fb1/format_3d: No such file or directory
Add missing chown system graphics /sys/class/graphics/fb1/video_mode (init.rhine.rc)
Add missing /sys/devices/virtual/graphics/fb1/hdcp/tp (ueventd.rhine.rc)
=> rhine: ramdisk: fix for video nodes

rootdir/ueventd.rhine.rc
introduced in commit: b6dbc4ef9f4912b6425a0f3c410612be3952711e
=> rhine: fix permission for video node

device.mk
added missing sensors permissions: Stepcounter
Stepdetector
https://drive.google.com/file/d/0B-e5eQvKq2t2VjUtRzV1TXpfbk0/view
=> rhine: update permissions

rootdir/init.rhine.rc
Launch QMUXD as root to enable it to obtain AP_BLOCK_SUSPEND
capability to acquire wakelock during suspend.
QMUXD will downgrade itself to user radio after getting the
necessary capabilities.
fix:
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not …
=> rhine: init: qmux: Launch QMUXD process as root user

BoardConfig.mk
This is needed in case sooner or later the default will change.
=> [Rhine] BoardConfig: Specify not to build any bootloader

rootdir/init.rhine.rc
also, add support for legacy paths
fix:
W/MediaScanner( 1123): Error opening directory '/storage/usbdisk/', skipping: Permission denied.
=> rhine: init: fix media scanner permissions

rootdir/system/etc/audio_effects.conf
actually in vendor/sony/qcom/prebuilt/proprietary/vendor/lib/soundfx we have 3 blobs provided by Sony (libqcbassboost.so, libqcreverb.so, libqcvirt.so) those are required by:
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L104
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L105
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L107
so adding them to audio_effects.conf for make them work
=> rhine: use proper qcom audio_effects

rootdir/system/etc/audio_policy.conf
=> rhine: add missing AUDIO_DEVICE_IN_REMOTE_SUBMIX

device.mk
those are defined in default.prop
=> rhine: remove duplicate art props

rootdir/init.rhine.rc
The operating system can detect when an application is reading
data sequentially from a file or from disk.
In such cases, it performs an intelligent read-ahead algorithm,
whereby more data than is requested by the user is read from disk.
Thus, when the user next attempts to read a block of data, it will
already by in the operating system's page cache.
The potential down side to this is that the operating system can
read more data from disk than necessary, which occupies space in
the page cache until it is evicted because of high memory pressure.
Having multiple processes doing false read-ahead would increase
memory pressure in this circumstance.
So, this change reduces read_ahead_kb value from 2048 to 512 then
this setting tells the operating system not to read extra bytes,
which can …
=> rhine: init: decrease read ahead buffer size

rootdir/init.rhine.pwr.rc
those are defined by init.rc see: http://pastebin.com/wA6ANDe4 (strings 363 to 385)
=> rhine: ramdisk: remove duplicated permissions to cpu

system.prop
on this commit: https://github.com/sonyxperiadev/kernel/commit/20a6eb95259e965b9cfa72cb156ac3f384d2c39a // we can see as our actual kernel is using 0X8010 for black instead 0X8080 who is gray
aosp is using 0X8080 on actual android-5.1.1_r4 branch: https://android.googlesource.com/platform/hardware/qcom/media/+/android-5.1.1_r4/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp (see string 129)
so change actual 0X8080 black with that one used by our kernel who is 0X8010 via prop persist.vidc.dec.conceal_color // commit 960a885dd7112b852c183ba5cad699ee24ae3a05 for platform/hardware/qcom/media
=> rhine: use proper black conceal color for our kernel 3.10

kernel-headers/uapi/linux/msm_mdp.h, kernel-headers/uapi/video/msm_hdmi_modes.h
As subject, there were some changes in the kernel and the
headers needs to be updated.
Updated headers:
* uapi/linux/msm_mdp.h
* uapi/video/msm_hdmi_modes.h
=> RHINE Update headers to reflect latest changes on 3.10 kernel

sepolicy/file_contexts
Correct and reorder logically sepolicy file paths and correct name for macaddrsetup in sepolicy/file_contexts
=> rhine: correct paths for sepolicy

rootdir/fstab.rhine
External sdcard is not an emulated sd.
line 69:
https://android.googlesource.com/platform/system/core/+/l-preview/fs_mgr/fs_mgr_fstab.c
=> rhine: fstab: Add flag to external sd mount

device.mk
on start of the system I can see a log saying:
E/qdhwcomposer (283): FATAL ERROR: copybit hw module not found --> avoid it building from source
=> rhine: build copybit

device.mk
needed for audio on android 6.0.0
more info: https://source.android.com/devices/audio/midi.html
=> rhine: Add MIDI support

overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
actually we are using that defined on: https://android.googlesource.com/platform/frameworks/base/+/android-6.0.0_r1/packages/SettingsProvider/res/values/defaults.xml#56
but the correct for marshmallow is defined on device/sample: https://android.googlesource.com/device/sample/+/android-6.0.0_r1/overlays/backup/frameworks/base/packages/SettingsProvider/res/values/defaults.xml#20
=> rhine: update backup service for apps

system.prop
This reverts commit 97ff6dcdcd823af88c1c7f8dcb061e2c79dc1639.
see: https://android.googlesource.com/platform/hardware/qcom/media/+/android-6.0.0_r1/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp#132
Conflicts:
system.prop
=> Revert "rhine: use proper black conceal color for our kernel 3.10"

device.mk
those already defined by aosp
librs_jni --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/generic_no_telephony.mk#38
com.android.future.usb.accessory --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/core_minimal.mk#35
e2fsck --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/core_minimal.mk#66
=> rhine: remove double packages

rootdir/ueventd.rhine.rc
following commit: 2e8884d3ff83d9c2800bb557e98266fb976372b9
=> rhine: ueventd: remove deprecated camera permissions

rootdir/init.rhine.rc
This change is part of:
https://android.googlesource.com/device/lge/hammerhead/+/38dcd1fc134a844e0e2f78b0e4e7e52a90afad79
=> rhine: Remove deprecated permission

device.mk
Bug: 20658562
Change-Id: Ib8e47b3edd94b1977c294959cdde01a54b64f123
Signed-off-by: Thierry Strudel <tstrudel@google.com>
=> rhine: Force dex2oat not to use swap file

rootdir/system/etc/media_profiles.xml
following nexus configuration for M
=> rhine: remove video editor from media_profiles

device.mk
all targets (amami honami and togari) are tracking aosp_base.mk & telephony.mk
well those are not including this: https://android.googlesource.com/platform/build/+/f29b5bd380e5ecced9bfa1d241e8b47448c29040%5E%21/#F
which let's without proper mms app on AOSP... so include it on our commons
=> rhine: compile new AOSP messaging app

overlay/frameworks/base/core/res/res/values/config.xml
Used by Google Play Services if available
=> rhine: let us use Google Provider for gps

rootdir/init.rhine.rc
Remove full arch path and call only lib name then the system
will preload it correctly.
=> rhine: Fix dynamic linker for boringssl-compat

rootdir/init.rhine.usb.rc
under developer options there is an option where user can choice about USB connection state one of these is charging mode only
which let's to charge the phone without enable adb services
=> rhine: Add charge only USB mode

device.mk
The variable persist.sys.usb.config is no longer honored by the framework,
and it's presence causes unnecessary toggling of the USB driver, which
disconnects ADB and makes the device's connection unstable.
Delete it.
=> rhine: Remove persist.sys.usb.config override

overlay/frameworks/base/core/res/res/values/config.xml
this is considered all the time by aosp and without this we finish with gps not working
re-add it to make it work
https://drive.google.com/file/d/0B-e5eQvKq2t2UGs2dVlYblhlSUU/view?usp=sharing
=> rhine: re-add aosp flp location provider

device.mk, rootdir/system/etc/media_codecs.xml, rootdir/system/etc/media_codecs_performance.xml
=> rhine: use hammerhead's media_codecs

sepolicy/file_contexts
it is exclusive of yukon and kanuti on aosp
https://github.com/sonyxperiadev/device-sony-yukon/blob/l-mr1/rootdir/init.yukon.rc#L365
https://github.com/sonyxperiadev/device-sony-kanuti/blob/l-mr1/rootdir/init.kanuti.rc#L393
=> rhine: sepolicy: don't label wcnss_service

rootdir/system/etc/media_profiles.xml
The current implementation does not support this resolution right now.
Signed-off-by: Julien Bolard <jbolard@genymobile.com>
=> rhine: disable 1080p resolution on back camera to avoid crash

sepolicy/file_contexts
[   10.766686] type=1400 audit(1608976.449:4): avc: denied { read } for pid=312 comm=applypatch name=mmcblk0p16 dev=tmpfs ino=10558 scontext=u:r:install_recovery:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1
[   10.803486] type=1400 audit(1608976.489:5): avc: denied { open } for pid=312 comm=applypatch path=/dev/block/mmcblk0p16 dev=tmpfs ino=10558 scontext=u:r:install_recovery:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1
[   10.829274] type=1400 audit(1608976.489:6): avc: denied { getattr } for pid=312 comm=applypatch path=/dev/block/mmcblk0p16 dev=tmpfs ino=10558 scontext=u:r:install_recovery:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1
=> rhine: set selabel for recovery device for install_recovery to access

sepolicy/init.te
Avoid
03-01 18:50:37.286 W/init    (1): type=1400 audit(0.0:4): avc: denied { write } for name=wcnss_wlan dev=tmpfs ino=11360 scontext=u:r:init:s0 tcontext=u:object_r:wcnss_device:s0 tclass=chr_file permissive=0
=> rhine: Fix wifi with Enforcing SELinux

device.mk
those are defined at qcom-vendor.mk in vendor files
=> rhine: remove vendor products

sepolicy/file_contexts, sepolicy/mediaserver.te
Avoid
22.277835] type=1400 audit(1453397071.649:11): avc: denied { write } for pid=310 comm=mediaserver name=delta dev=mmcblk0p25 ino=390981 scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   22.277928] type=1400 audit(1453397071.649:12): avc: denied { add_name } for pid=310 comm=mediaserver name=Bluetooth_cal.acdbdelta scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   22.278041] type=1400 audit(1453397071.649:13): avc: denied { create } for pid=310 comm=mediaserver name=Bluetooth_cal.acdbdelta scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   22.278129] type=1400 audit(1453397071.649:14): avc: denied { open } for pid=310 comm=mediaserver …
=> rhine: SELinux for acdb files

kernel-headers/linux/pn547.h, kernel-headers/sound/compress_params.h
reflect current LA.BF64.1.2.2_rb4.7 kernelheaders
Testbuild succeeded on Amami
=> rhine: update kernel headers

rootdir/init.rhine.rc
readahead values:
sonyxperiadev/kernel@02246ee
=> rhine: init: Use predefined readahead values from kernel

rootdir/system/etc/audio_effects.conf
not using
pre_processing {
voice_communication {
aec {
}
ns {
}
}
}
it is specific for hammerhead
=> rhine: use hammerhead's audio_effects

rootdir/init.recovery.rhine.rc
link to /dev/block/bootdevice else in recovery partitions are not mountable.
tested on TWRP recovery
=> recovery: add missing symlink

rootdir/init.rhine.pwr.rc, rootdir/ueventd.rhine.rc
as suggested in: https://github.com/sonyxperiadev/device-sony-common/pull/42
=> Rhine: add simple cpuquiet / rqbalance permissions

rootdir/init.rhine.pwr.rc
Fix and move simple power HAL permissions to "on init" stage
then it will also be able early to LPM mode.
Fix:
05-16 10:39:00.817  1027  1048 I Simple PowerHAL: Device is asleep.
05-16 10:39:00.817  1027  1048 I Simple PowerHAL: Setting low power
mode
05-16 10:39:00.817  1027  1048 E Simple PowerHAL: Error opening
/sys/devices/system/cpu/cpuquiet/rqbalance/balance_level: Permission
denied
05-16 10:39:00.817  1027  1048 E Simple PowerHAL: Error opening
/sys/devices/system/cpu/cpuquiet/rqbalance/nr_run_thresholds: Permission
denied
05-16 10:39:00.817  1027  1048 E Simple PowerHAL: Error opening
/sys/devices/system/cpu/cpuquiet/rqbalance/nr_down_run_thresholds:
Permission denied
=> rhine: Fix simple power HAL permissions

platform.mk
there is not windy device in rhine family so it can be defined in rhine-common
=> Rhine: Build Stk

PlatformConfig.mk, rootdir/init.rhine.pwr.rc, rootdir/ueventd.rhine.rc, system.prop
Core limiting via msm_performance works well, but cpuquiet absolutely
hates it. rqbalance is not aware of msm_performance so it spams dmesg
because it cannot online a core for 'unknown' reasons.
We can achieve the same result using cpuquiet which rqbalance is
aware of. We can also have two sources of core limiting, power
profile and thermal.
We also need to tune rqbalance and cpuquiet per platform so also
move their system props.
=> Move sysfs and props for cpuquiet hotplugging

rootdir/ueventd.rhine.rc
[    7.463925] ueventd: invalid line ueventd.rc line for '/dev/ttyHSL2'
=> rhine: remove IR_REMOTE_CONTROL device

rootdir/ueventd.rhine.rc
those are not present here also rhine has only pn544 chip
=> rhine: remove uneeded nfc devices

bluetooth/bdroid_buildcfg.h
Use ro.boot.hardware property and naming BT dynamically.
Change-Id: I5ec4d262af3d0e55d9f93fdb3ca4e0d6e49dbc8f
=> [m-mr1] sony: rhine: Set BT default name dynamically

bluetooth/bdroid_buildcfg.h
Use ro.boot.hardware property and naming BT dynamically.
Change-Id: I5ec4d262af3d0e55d9f93fdb3ca4e0d6e49dbc8f
=> [master] sony: rhine: Set BT default name dynamically

system.prop
Tune rqbalance to linearize CPU hotplugging and optimize power
consumption while retaining performance.
=> [RHINE] system.prop: Tune rqbalance parameters

rootdir/fstab.rhine
Android Nougat changed how it communicates with the recovery
partition. Until now the recovery commands had been written
to the /cache partition, but this has changed. Now recovery
writes to the /misc partition.
Fortunately for rhine devices we actually have
an empty and unused /apps_log partition we can use.
=> fstab: Allow recovery to use the misc partition

rootdir/init.rhine.rc
Following kitakami: https://github.com/sonyxperiadev/device-sony-kitakami/commit/f945af43f8e70edb46f20b33dcae0ec10e6249da
=> rhine: Add support for top-app cpuset

rootdir/init.rhine.rc
init: write_file: Unable to write to '/dev/cpuset/foreground/boost/cpus': Permission denied
/dev/cpuset/foreground/boost/cpus is not defined in init.rc by AOSP .... set in platform for correct use
so move cpuset from boot to init
=> rhine: fix cpus permissions for CPUSETS

rootdir/init.rhine.rc
Write the bluetooth macaddr to a place that is natively readable
by bluetooth services, instead of creating new locations which
requires excessive permissions.
=> macaddr: remove dangerous sepolicy permissions

rootdir/ueventd.rhine.rc
match common lcd brightness and max_brightness
https://github.com/SonyAosp/device_sony_common/blob/android-7.1/liblights/lights.c#L58
https://github.com/SonyAosp/device_sony_common/blob/android-7.1/liblights/lights.c#L61
=> rhine: ueventd: Add common lights sysfs path

PlatformConfig.mk, platform.mk
* Avoid hardcoding the paths by using common
variables declared once for path accesses
Change-Id: I81226a249c6258360c540c80ae4dfe5073439921
Signed-off-by: Adrian DC <radian.dc@gmail.com>
=> rhine: config: Use unique variables for device paths

platform.mk
needed for com.android.nfc_extras package
=> rhine: add missing nfc_extras permission

PlatformConfig.mk, sepolicy_platform/file_contexts
We have	removed	the dev	block nodes from the common repository
device-sony-sepolicy's file_contexts because it was really
getting too much dirty.... and also, now that UFS has appeared
we had a conflict: on those devices, mmcblk0 is	SDCard,	while
on eMMC	devices	it is the eMMC.
This file_contexts contains only the correct and necessary
block node contexts for	this platform.
=> Add platform-specific file_contexts

rootdir/init.rhine.rc
Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online.
Change-Id: I645d22e899735415cc15c821042c4df3b0f169a4
=> sony: rhine: Increase max number of compression streams
