sonyxperiadev/device-sony-rhine

rootdir/system/etc/gps.conf
GPS lock in ~10 seconds versus ~90+ seconds
=> gps: enable XTRA servers for quick A-GPS lock

device.mk, kernel-headers/sound/audio_effects.h, kernel-headers/sound/compress_offload.h, kernel-headers/sound/compress_params.h, rootdir/system/etc/audio_effects.conf, rootdir/system/etc/audio_policy.conf, rootdir/system/etc/media_codecs.xml, rootdir/system/etc/media_profiles.xml
this fixes audio playback bugs, for example an unresponsive device
h264 decoding is still broken btw
=> rhine: sync audio and codecs with hammerhead

rootdir/init.rhine.pwr.rc, rootdir/init.rhine.rc
this commit also improve boot time and remove old cruft
=> udpate power management sysfs path

BoardConfig.mk
As per comments in IRC, move the dtbs files to out directory for kernel mkqcdbootimage command path.
=> Move dtbs files to out directory.

rootdir/init.rhine.rc
https://github.com/android/platform_system_core/commit/5c3c77ed7855d262645c44b7e239476d9b66393d
=> init.rhine.rc: Remove WiFi directory creation

BoardConfig.mk
to reduce power consumption after charging completion
=> rhine: Enable charger suspend

rootdir/init.rhine.rc, rootdir/ueventd.rhine.rc
these entries are present on honami at least
=> rhine: add more video permissions

BoardConfig.mk, README.md, device.mk, rootdir/init.rhine.rc, system.prop
=> rhine: Sources cleanup

device.mk
Remove old and deprecated packages
=> rhine: Package cleanup

rootdir/fstab.rhine
more info: https://source.android.com/devices/storage/adoptable.html & https://source.android.com/devices/storage/config.html#android_6_0
=> rhine: adoptable MicroSD

device.mk
Enable MultiWindow as described here:
http://forum.xda-developers.com/showpost.php?p=63230682&postcount=85
=> rhine: enable MultiWindow

rootdir/init.rhine.pwr.rc, rootdir/init.rhine.rc
=> rhine: Move power stuff to pwr.rc

overlay/frameworks/base/core/res/res/values/config.xml
more info: https://github.com/android/platform_frameworks_base/commit/8c621ef54630e411d50e9ba1d8d8ed19ef93f9e1
=> shinano: Add support for static RadioCapabilities

device.mk
=> rhine: Add new camera2 hardware features

sepolicy/zygote.te
Avoid
01-05 22:37:59.439   325   325 I main    : type=1400 audit(0.0:23): avc: denied { listen } for path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
01-05 22:38:01.089   850   850 I main    : type=1400 audit(0.0:24): avc: denied { getopt } for path=/dev/socket/zygote scontext=u:r:system_server:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
01-05 22:38:10.719   325   325 I main    : type=1400 audit(0.0:25): avc: denied { accept } for path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
01-05 22:38:10.729   325   325 I main    : type=1400 audit(0.0:26): avc: denied { setopt } for path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 …
=> rhine: add zygote policy

rootdir/fstab.rhine
=> fstab: Fix USB OTG XHCI path for USB HDD mount

sepolicy/mediaserver.te
part of commit: 51b65ece1c24697b84e29b0a1a2677b01de9ca21
=> rhine: update acdb SELinux

BoardConfig.mk, device.mk
adds unified includes to family .mk
=> clean inclusion

platform.mk
=> rhine: cleanup device.mk

rootdir/ueventd.rhine.rc
=> rhine: add permissions for hw effects

platform.mk
=> Rhine: Build InCallUI

platform.mk
=> Rhine: RILD: cleanup

rootdir/ueventd.rhine.rc
https://www.osadl.org/UIO.uio0.0.html
=> rhine: add UserSpace I/0 (UIO) permissions

rootdir/init.rhine.rc, rootdir/ueventd.rhine.rc
=> rhine: add missing FM permissions

rootdir/fstab.rhine, rootdir/init.rhine.rc
This can give a nice performance boost under heavy load
=> Configure Zram on rhine devices

PlatformConfig.mk, platform.mk
Needed Patches
https://android-review.googlesource.com/#/q/topic:sony-hal1+(status:open+OR+status:merged)
=> rhine: enable legacy camera fixes
